### ISSUE TITLE
method of application

### ISSUE THREAD

**Issue by genbei** [wangqiangneu/dlcl#4]
Excuse me, can I use transformer-DLCL  like transformer , how to operate it concretely, and whether I can call it directly? My code is tensorflow

**Comment by wangqiangneu** [comment]
> Excuse me, can I use transformer-DLCL like transformer , how to operate it concretely, and whether I can call it directly? My code is tensorflow

I'm not sure what your problem is. If you want to run DLCL in TensorFlow, you should rewrite the implementation by TensorFlow because our codebase is based on PyTorch. 

Actually, the implementation of DLCL is not complex, and welcome to contribute your tensorflow code of DLCL.
